### PR TITLE
API improvements

### LINKED ISSUE #26: API improvements
A couple ideas to improve the API of the package:

`RegisterCheck` should accept a check and a config separately: `RegisterCheck(check Check, cfg *Config) error`

This would allow making the config optional (given the health checker accepts a default config applied to all checks). I realize this might not make sense in all cases, but it would give the user a cleaner API when they get to learn the package.

I could even imagine

```go
RegisterCheck(check Check) error
RegisterCheckWithConfig(check Check, cfg Config) error
```

Or with functional options:
```go
type CheckOption interface {
    applyCheck(check *check)
}

RegisterCheck(check Check, ...CheckOption) error
```

(Note: #25 implements functional options, this would work on top of that)

---

Consider dropping deregistration: is it really a useful feature? Making the health checker mutable this way is confusing and prone to error in my opinion. Obviously, if there is a legitimate use case it should stay.

As a consequence, I'd also add a `Start` (and `Stop`?) method to the health checker and make `RegisterCheck` return an error for a started health checker.

Alternatively, create a separate `HealthBuilder` that's mutable and build a HealthChecker with the builder that's immutable.

---

I realize these are huge changes, but in the long run these could improve the package API by making it more obvious and compact.

### PR DESCRIPTION
**Pull request by sagikazarmark**
Fixes #26

### CODE REVIEW

**Comment by eranharel** [comment]
Thanks @sagikazarmark 
I'll try to find time to review this soon

**Comment by sagikazarmark** [comment]
If I can have a suggestion: each commit is buildable and reviewable separately and there are a lot of changes, so reviewing each commit separately might be a little bit easier.

**Comment by sagikazarmark** [comment]
Ping @eranharel 🙂

**Comment by sagikazarmark** [comment]
Ping @eranharel

I'm hoping this can be merged before other PRs, because rebasing it would be a lot of work. :\

**Comment by eranharel** [comment]
I'm really trying to get to this. Got flooded at work, sorry

**Comment by sagikazarmark** [comment]
Friendly ping. 🙂

**Comment by eranharel** [comment]
@sagikazarmark sorry for the delay in reviewing this, I'm really overloaded at work...

Is there any chance of splitting this MR into smaller MRs?
I'm asking because I'm having a hard time reviewing this as a whole. There are several unrelated activities in this MR, and some are controversial. If we start a huge discussion here on everything it will never end.

I see here:
* Test stabilization
* New features (config API changes, defaults changes, etc)
* Refactoring
  * dependencies changes
  * renamings
  * moving of packages
  * moving of interfaces
  * etc

I can't say I agree with everything here, so if you agree to split the MR I think we can complete this quicker and move to the next MR in line.

**Comment by sagikazarmark** [comment]
@eranharel this is exactly why I suggested reviewing commits instead of the PR as a whole. I can submit them in smaller PRs, but since subsequent commits depend on each other I'll have to do it one step at a time.

If it helps speeding up the review, I can send them in smaller chunks.

**Comment by sagikazarmark** [comment]
@eranharel submitted 4 smaller PRs. The last one will have to wait at least until #40  and #42 are merged.

**Comment by sagikazarmark** [comment]
All PRs are merged, closing.

There is one change left to be added @eranharel , but it depends on tagging the main library. After that, I can submit a patch to the opencensus library.

**Comment by eranharel** [comment]
Waiting for @dmarkhas to complete his PR, and then I'll tag

**Pull request closed without merging**
