### PR TITLE
Refactor metrics and packages

### PR DESCRIPTION
**Pull request by bivas**
Major Changes:
- Change the new API to implement the options pattern
- Added option to change health object classification (enable the creation of multiple Health objects for the same server)
- Refactor stats and views to internal package to support classification and measurement prefix
- Disable travis-ci 😞 

Minor Changes:
- Split `health.go` to multiple files per component
- Extract `Result` to be an internal type as it shouldn't be available to the user

**Breaking Changes**
- Changed the main package to conform to package name
    - This might not break current clients as most IDEs auto-alias the original import to `health` and as a result any change is transparent (tested with current client implementation)
- Removed `WithCheckListener` from `Health` interface and migrated it to be an `Option`
- Added `Views()` method to `Health` interface

### CODE REVIEW

**Comment by sagikazarmark** [comment]
These seem to be rather large changes, mixing refactors, new features and breaking changes. I wonder if separate PRs would be better for future tracking and separate discussions.

As for the changes themselves, I have a couple reservations:

- Why have some types been moved to a central types package? It fractures the package interface IMHO
- Some public interfaces (eg. `CheckListener`) reference types in an internal package which means that external packages won't be able to implement that interface. In general, public types should never reference internal or unexported types.
- Exposing metrics views from the health checker doesn't seem like a good idea to me. It ties the health checker even more to the metrics solution. Please see my suggestions in #24
- Classification seems like a Kubernetes specific thing. I've always used gosundheit for readiness checks and a simple handler responding "ok" as a liveness check. Can you provide a use case when this classification is useful?
- Huge +1 for functional options, although I usually prefer options to be an interface with an apply function. (You can read more about it in my blog: https://sagikazarmark.hu/blog/functional-options-on-steroids/)

**Comment by bivas** [comment]
@sagikazarmark Thank you for a very elaborated review. Highly appreciate it 👍🏼 
Regarding your comment on the size of this PR - you're right. I had mixed feelings about it, but to make the fastest progress, I combined all the requirements in a single PR (Just FYI, I work with @eranharel on this project and these changes/requirements are coming from our developers) but due to the nature of our work - it might have taken really long time to review and merge each one (as each change might relate to another).

* I liked the idea presented in #24 - I'll modify my metrics solution to match your recommendation. 
* Types where moved to central location to prevent cyclic import (main->metrics->main). If we'll use the solution you offered, they can be moved back to the main package.
* Classification is indeed a Kuberenetes concept, and you're also correct that usually a simple 'OK' response is enough. I would even argue that `setup` classification is not suitable due the nature of the check (usually blocking). But again, the `liveness` classification is coming from our users - we added it just to simplify their usage (e.g. multiple health registries)
* I'm familiar with the `apply` approach for `Option` - I felt that it's not fully fitting this scenario. 

I will update the PR and hopefully it will be a better fit with both our needs.

**Comment by bivas** [comment]
In order for us to discuss these items in small scope - I'll close this PR and open separate ones per change.

**Comment by sagikazarmark** [comment]
@bivas glad I could help! I answered a couple comments below, but we can discuss things in new PRs/issues as well.

> I liked the idea presented in #24 - I'll modify my metrics solution to match your recommendation.

I had quite a few ideas in #24. How do you plan to proceed? Maybe leave a comment there?

> But again, the liveness classification is coming from our users - we added it just to simplify their usage (e.g. multiple health registries)

My first attempt would be documenting best practices. Eg. a multi-health-checker approach. If adding classification to metrics is a requirement, it could be a parameter of the metrics implementation. Overall, I think adding this concept to the entire library would complicate things and would make a relatively simple library/use case unnecessarily complicated.

> I'm familiar with the apply approach for Option - I felt that it's not fully fitting this scenario.

I think it would make sense if you consider my recommendations in #26. For example: an `ExecutionPeriod` config could be a valid option for both the health checker (to provide a default for all checkers) and the check registration. In that case, having an `applyHealthChecker` and `applyCheck` function for the same option would be a better solution in my opinion.

Having an interface by default is also low cost and extendable, while having a function is not (and some could say changing it is a breaking change).

**Pull request closed without merging**
